name: Compilar Mod para Celulares

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android 32-bit
            target: Android32
          - name: Android 64-bit
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      # Instalamos dependencias necesarias para compilar
      - name: Instalar Dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake

      # Configurar el SDK de Android (si es necesario)
      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      # Tarjetas de compilación del mod
      - name: Compilar Mod
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DTARGET=${{ matrix.config.target }}
          cmake --build build --config Release

      # Subir archivo compilado
      - name: Subir Archivo Compilado
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.target }}
          path: build/*.geode
